### ISSUE TITLE
Invalid  Synthax

### ISSUE THREAD

**Issue by aliyurtsevenn** [maximtrp/scikit-posthocs#32]
**Describe the bug**

**Dataset**
Please provide a link to the dataset you get the bug with.

**To Reproduce**

**Expected behavior**

**System and package information (please complete the following information):**
- OS: (e.g. Linux 4.20.0-arch1-1-ARCH x86_64 GNU/Linux)
- Package version: (e.g. 0.4.0)

**Additional context**

**Comment by aliyurtsevenn** [comment]
Hello, 

I tried to import scikit_posthocs and this error came out:

Traceback (most recent call last):
  File "/home/a/Desktop/projects/statistics_analyzer/new.py", line 16, in <module>
    import scikit_posthocs
  File "/usr/local/lib/python3.7/dist-packages/scikit_posthocs/__init__.py", line 16, in <module>
    from scikit_posthocs._plotting import sign_array, sign_plot, sign_table  # noqa
  File "/usr/local/lib/python3.7/dist-packages/scikit_posthocs/_plotting.py", line 4, in <module>
    from seaborn import heatmap
  File "/usr/local/lib/python3.7/dist-packages/seaborn/__init__.py", line 16, in <module>
    from .widgets import *
  File "/usr/local/lib/python3.7/dist-packages/seaborn/widgets.py", line 7, in <module>
    from ipywidgets import interact, FloatSlider, IntSlider
  File "/usr/lib/python3/dist-packages/ipywidgets/__init__.py", line 23, in <module>
    from IPython import get_ipython
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/usr/lib/python3/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 124, in <module>
    from IPython.utils import path as util_path
  File "/usr/lib/python3/dist-packages/IPython/utils/path.py", line 18, in <module>
    from IPython.utils.process import system
  File "/usr/lib/python3/dist-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/usr/lib/python3/dist-packages/IPython/utils/_process_posix.py", line 24, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax


May you inform me why I cannot import scikit_posthocs and give me any directions?

Thank you in advance.

**Comment by maximtrp** [comment]
Hello! Seems like an error in **pexpect** package. Are you using a recent version? You may try to update it or create a virtual environment with the latest versions of the required packages.

Could you please post the output of `pip freeze`?

**Comment by aliyurtsevenn** [comment]
Thank you for your help! I updated pexpect and it worked.

**Comment by maximtrp** [comment]
@aliyurtsevenn You are welcome!
